<?php

/**
 * Implements hook_block_info().
 */
function worxco_footer_block_info() {
  $blocks['worxco_footer'] = array(
    'info' => t('Worxco Footer'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function worxco_footer_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'worxco_footer':
      $block['subject'] = t('<none>');
      global $user;
      $output = '<p>&copy;' . date('Y') . ' <strong>' . variable_get('site_name', 'Drupal') . '</strong>. - All Rights Reserved<br />';
      if ($user->uid == 0) {
        $output .= '<a href="/user">Site Admin Login</a>';
      } else {
        $output .= '<a href="/user/logout">Logout</a>';
      }   
      $output .= ' | Developed by <a href="http://worxco.com/" target="_blank">the Worx Company</a> | Hosted by <a href="http://www.hostofamerica.com/" target="_blank">Hosts of America</a></p>';
      $block['content'] = $output;
      break;
    }

    return $block;
}
